server:
  port: 8083

spring:
  application:
    name: delivery-service

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:deliverydb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
